[package]
name = "lib_crystal_matrix"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
lazy_static = "1.5.0"
bincode = "1.3.3"
